services:
  - type: web
    name: shadow-chat-backend
    env: go
    region: oregon
    buildCommand: go build -o bin/shadowchat-backend ./cmd/server
    startCommand: ./bin/shadowchat-backend
    envVars:
      - key: JWT_SECRET
        value: mysecret123
      - key: ALLOWED_ORIGIN
        value: "*"
